# Simulating Coin Flips

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# outcome of one coin flip
np.random.randint(2)

1

In [3]:
# outcome of ten thousand coin flips
np.random.randint(2, size = 10000)

array([1, 0, 1, ..., 1, 1, 0])

In [4]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size = 10000).mean()

0.4992

In [5]:
# outcome of one coin flip
np.random.choice([0,1])

1

In [6]:
# outcome of ten thousand coin flips
np.random.choice([0,1], size = 10000)

array([0, 0, 1, ..., 0, 0, 0])

In [7]:
# mean outcome of ten thousand coin flips
np.random.choice([0,1], size = 10000).mean()

0.5002

In [8]:
# outcome of ten thousand biased coin flips
np.random.choice([0,1], size = 10000, p = [0.8, 0.2])

array([1, 0, 0, ..., 0, 0, 1])

In [9]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size = 10000, p = [0.8, 0.2]).mean()

0.2029